replicaCount: 1

image:
  repository: controller
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

leaderElect: true

metrics:
  enabled: true
  port: 8443

healthProbe:
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

serviceAccount:
  create: true
  name: ""
