---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tapir.tapir.dev
  resources:
  - tapirclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tapir.tapir.dev
  resources:
  - tapirclusters/finalizers
  verbs:
  - update
- apiGroups:
  - tapir.tapir.dev
  resources:
  - tapirclusters/status
  verbs:
  - get
  - patch
  - update
