name: Operator E2E Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'kubernetes/operator/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'kubernetes/operator/**'

defaults:
  run:
    working-directory: kubernetes/operator

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: kubernetes/operator/go.mod

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
