name: Test SurrealKV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: surrealdb/surrealkv
          path: ../surrealkv
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.93.0
          components: clippy
      - name: Test
        run: make ci/test-surrealkv
